### PR TITLE
Change DropBehavior to have associated const instead of function.

### PR DESCRIPTION
**Pull request by ShaneEverittM**
This change is [Reviewable](https://reviewable.io/reviews/jonhoo/rust-evmap/87)

### CODE REVIEW

**Comment by Eh2406** [comment]
cc #85

**Comment by jonhoo** [comment]
Ah, excellent, thank you! This is going to require a breaking change for `left-right`, so could you please update `evmap` to have a `path` dependency on `left-right` as well, and then fix the resulting error in `evmap` (specifically its `impl DropBehavior` blocks also have to change).

**Review by jonhoo — APPROVED** [review]
Looks great, thank you! I'll do a release of `left-right` shortly, since I think we should get this change out sooner rather than later.

**Comment by ShaneEverittM** [comment]
Cool! First PR ever!

**Comment by jonhoo** [comment]
Published in `left-right 0.11` and `evmap 11.0.0-alpha.5` :tada:

**Pull request merged**
